name: 'Auto Publish'

description: 'Automatically publish to NPM and create Github release'

inputs:
  github-token:
    description: "Your Github token, it's already available to your Github action"
    required: false
    default: ${{ github.token }}
  npm-token:
    description: 'Your Npm Publish token, if you do not wish to publish to Npm, skip this'
    required: false
  build-command:
    description: 'The bash command to execute after the version bump and before opening the PR'
    required: false
  optic-url:
    description: 'URL if you have a custom application that serves OTP'
    required: false
    default: 'https://optic-zf3votdk5a-ew.a.run.app/api/generate/'
  optic-token:
    description: 'Your Optic token. You can add your Npm secret to the Optic app, generate a new token and pass it to this input. Required only if you want to pubish to Npm and have MFA enabled for your account'
    required: false
  actor-name:
    description: 'The name you want to see in the new release commit.'
    required: false
    default: '${{ github.actor }}'
  actor-email:
    description: 'The email you want to see in the new release commit'
    required: false
    default: 'actions@users.noreply.github.com'
  semver:
    description: 'The semver to use for this new release'
    required: true
    default: 'patch'
  npm-tag:
    description: 'If you want to release to the Npm with a custom tag, pass it here'
    required: false
    default: 'latest'
  api-url:
    description: 'Url of the API where the application is running'
    required: false
    default: 'https://optic-release-automation-ocrlhra4va-ue.a.run.app/'
  app-name:
    description: 'Name of the github app that authors optic PRs in the following format: `app-name[bot]`'
    required: false
    default: 'optic-release-automation[bot]'
  sync-semver-tags:
    description: 'If you want to keep the major and minor versions tag synced to the latest appropriate commit'
    required: false
    default: 'false'
  commit-message:
    description: 'The commit message template. The keyword "{version}" will be replaced with the new version'
    required: false
    default: 'Release {version}'
  revert-commit-after-failure:
    description: 'If the release fails while publishing to NPM and to GitHub, setting this flag to "true", will revert the release commit. When using this flag, make sure the action is able to push directly to the main branch'
    required: false
    type: boolean
    default: 'false'
  notify-linked-issues:
    description: 'If the flag is set to "true", a comment will be posted on each issue that is linked to the pull requests included in each release. The default setting is "true".'
    required: false
    type: boolean
    default: 'true'
  artifact-path:
    description: 'Set this input to the distribution folder or file you want to add as the main asset for your release. It will be downloadable from the release page and a preview of it will be available in the pull request.'
    required: false
  version-prefix:
    description: 'A prefix to apply to the version number, which reflects in the tag and GitHub release names'
    required: true
    default: 'v'
  prerelease-prefix:
    description: 'A prefix to apply to the prerelease version number'
    required: false
  base-tag:
    description: 'This input allows you to specify a base release and will include all changes made in releases between the base release and the latest release'
    required: false
  provenance:
    description: 'If true, NPM >9.5 will display a "provenance" badge (https://github.blog/2023-04-19-introducing-npm-package-provenance/). The default setting is "true".'
    required: false
    type: boolean
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout the fresh project
      uses: actions/checkout@v3

    - name: Configure git
      run: |
        git config --global user.email "${{ inputs.actor-email }}"
        git config --global user.name "${{ inputs.actor-name }}"
      shell: 'bash'

    - name: Version bump
      uses: actions/github-script@v6
      id: version-bump
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        result-encoding: string
        github-token: ${{ inputs.github-token }}
        script: |
          const { bumpVersion } = require('${{ github.action_path }}/dist/index.js')
          return await bumpVersion({ inputs: ${{ toJSON(inputs) }} })

    - name: Build the package
      if: ${{ inputs.build-command }}
      run: |
        node -v
        npm -v
        ${{ inputs.build-command }}
      shell: 'bash'

    - name: Commit and open PR
      uses: actions/github-script@v6
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { runAction } = require('${{ github.action_path }}/dist/index.js')
          await runAction({ github, context, inputs: ${{ toJSON(inputs) }}, packageVersion: ${{ steps.version-bump.outputs.result }} })

    - name: Release the package
      uses: actions/github-script@v6
      if: ${{ github.event_name == 'pull_request' }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { runAction } = require('${{ github.action_path }}/dist/index.js')
          await runAction({ github, context, inputs: ${{ toJSON(inputs) }} })
