name: 'Auto Publish'

description: 'Automatically publish to NPM and create Github release'

inputs:
  github-token:
    description: "Your Github token, it's already available to your Github action"
    required: true
  npm-token:
    description: "Your Npm Publish token"
    required: true
  optic-url:
    description: "URL if you have a custom application that serves OTP"
    required: false
    default: "https://optic-zf3votdk5a-ew.a.run.app/api/generate/"
  optic-token:
    description: "Your Optic token. You can add your Npm secret to the Optic app, generate a token and pass it to this input"
    required: true
  actor-name:
    description: "The name you want to see in the new release commit."
    required: false
    default: "${{ github.actor }}"
  actor-email:
    description: "The email you want to see in the new release commit"
    required: false
    default: "actions@users.noreply.github.com"
  semver:
    description: "The semver to use for this new release"
    required: true
    default: "patch"
  npm-tag:
    description: "If you want to release to the Npm with a custom tag, pass it here"
    required: false
    default: "latest"
  api-url:
    description: "Url of the API where the application is running"
    required: false
    default: "https://smee.io/VceC5459wnYhIob/"

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: |
        git config --global user.email "${{ inputs.actor-email }}"
        git config --global user.name "${{ inputs.actor-name }}"
        npm config set //registry.npmjs.org/:_authToken=${{ inputs.npm-token }}
        npm install
      shell: 'bash'
    - uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const script = require('${{ github.action_path }}/action.js')
          await script({ github, context, core, inputs: ${{ toJSON(inputs) }} })
